### ISSUE TITLE
Reconsider the allowed list of elements and attributes

### ISSUE THREAD

**Issue by lnicola** [notriddle/ammonia#54]
See https://www.reddit.com/r/rust/comments/72kp3c/ammonia_100rc1_an_html_sanitization_crate/dnjdxpn/. Changing the defaults is arguably a breaking change, so we might want to do it before the stable release.

**Comment by notriddle** [comment]
I think I originally set the defaults so that everything pulldown-cmark could emit would pass through unmolested. Not a very good reason, I guess.

[Here's what crates.io sets it to](https://github.com/rust-lang/crates.io/blob/master/src/render.rs#L14-L105)

* Tags: a b blockquote br code dd del dl dt em h1 h2 h3 hr i img input kbd li ol p pre s strike strong sub sup table tbody td th thead tr ul hrspan
* Tag attributes:
  * a: href target
  * code: class
  * img: width height src alt align
  * input: checked disable type
* Allowed classes:
  * code: language-bash language-clike language-glsl language-go language-ini language-javascript language-json language-markup language-protobuf language-ruby language-rust language-scss language-sql yaml
* Link rel="nofollow noopener noreferrer"

For awhile, I wanted to set Ammonia's defaults to be the same as Crates's, but the have stuff like code-classes and input-checked which aren't applicable to all webapps. So I didn't bother.

**Comment by lnicola** [comment]
Sanitizing Markdown is one use-case; others I can imagine are applications like feed readers, comment sanitization and general page cleanup/restyling à la `readability.js`. @ssokolow probably had something else in mind. 

I think one of the main points here is that changing the whitelist will break compatibility.

**Comment by ssokolow** [comment]
My main concern is that most users aren't going to do the kind of research I did in order to figure out what to allow, which means that one of the following is likely to happen:

1. They'll only use the sanitizer in places *they* think it's needed, rather than everywhere that could be accessed via an HTTP-exploitable vulnerability. (The configuration I mentioned is good for running a blanket filter for XSS and related exploits on everything that can be changed without SSH access.)

2. They'll broaden the sanitizer by adding whatever tags they personally need (eg. `video`), give it a test or two, and call it working without realizing that they've left a lot of corner cases broken.

3. They'll broaden the sanitizer without understanding the attacks being defended against and open themselves up to attack.

That's why "Allow everything that can't be used to execute JavaScript except for tags that only make sense in the site template, default to `noopener`, etc." is a good default.

**Comment by notriddle** [comment]
BTW, Ammonia already defaults to "noopener". The main reason for recommending that you turn it on is to make sure that, if somebody wants to add nofollow (which is not on by default), they should do this:

    builder.link_rel(Some("noopener noreferrer"))

Instead of turning noopener off because they've never heard of it.

**Comment by ssokolow** [comment]
That reminds me. You might want to make it more clear to people who are minimally familiar with `rel` that it's a space-separated list.

I'm a little dozy right now and, looking at the docs, it took me a moment longer than it should have to remember that I was looking at an "any combination of these" list (ie. bitfield-like) rather than a "pick one" list (ie. enum-like).

**Comment by ssokolow** [comment]
Here are some attributes that got missed in that commit... probably because I just summarized most of them as being ones "specific to the elements I listed".

Here are the relevant ones I'm allowing in my sanitizer config at the moment:


### Necessary for the proper function of the element

* `<bdo dir="">` is necessary to actually specify the text directionality to be forced.
* `<col span="">` and `<colgroup span="">` are used to set `colspan` for multiple table cells at once.

### Deprecated elements which may still be produced by certain HTML generators

* `<hr>` can accept `align`, `size`, and `width` as a pre-CSS solution that I think I remember a TinyMCE plugin generating.
* `<tr>`, `<th>`, `<td>`, `<thead>`, `<tbody>`, `<tfoot>`, `<table>`, `<col>`, and `<colgroup>` can accept `align`, `char` and `charoff` to implement the deprecated/obsolete way of doing an alignment mode that is supported in everything except Firefox according to MDN.
