### ISSUE TITLE
Fine customization of settings is not possible

### ISSUE THREAD

**Issue by lnicola** [notriddle/ammonia#57]
There's no way for a user to add or remove a single element from the allowed list. There's also no way of obtaining the list that's currently configured.

We should probably add some methods like `.allow_element()` on the `Builder` unless we go for a different API.

CC @ssokolow, since this is partly inspired by his review.

**Comment by ssokolow** [comment]
In my view, this would be an essential first step to allowing new elements to be added to the default whitelist without it being a breaking change:

1. Offer users the choice between "start with the defaults, then modify" and "build a whitelist from scratch" so that the latter can be the recommended option for things like comment forms or situations where users want complete control.
2. Define a clear policy for what does and doesn't go on the default whitelist. (eg. Perhaps `video` and `audio` should be allowed for consistency with `img`, but a default URL filter should be in place which only allows local resources... or perhaps `img` should be disallowed based on a default policy of refusing all subresource references.)
3. Allow fine customization so users can easily ask for things like "Defaults, but also allow `script` tags pointing at GitHub Gist and `iframe` tags pointing at Youtube". (So, `.allow_element()` plus some kind of URI filter)
3. Users who opt to start from the defaults can upgrade ammonia to automatically get support for new safe HTML elements like `time` and `data` (added in HTML5) as they're added.

Ideally, you'd also offer an easy way for users to copy-paste a definition of the defaults which they can embed in their program and customize.

**Comment by ssokolow** [comment]
Also, one interesting idea to consider would be support for a URL filter which works by parsing a Content-Security-Policy definiion, similar to how LXML offers a module which instantiates XPath objects from CSS selector strings. 

It wouldn't allow specifying restrictions more granular than allowed domains unless you support chaining multiple URL filters, but it would provide a great way to allow a single authority on things like where `<img src="">` may point across the entire application, minimizing the chance that security definitions fall out of sync or get neglected. (And it'd be less footgun-y than regexp syntax.)

(Plus, combined with defaults suitable for running ammonia on everything in the site not requiring SSH to edit, it would help to act as a polyfill for browsers which haven't implemented CSP or have implemented it in an incomplete fashion.)

**Comment by gengjun** [comment]
> 3. Allow fine customization so users can easily ask for things like "Defaults, but also allow `script` tags pointing at GitHub Gist and `iframe` tags pointing at Youtube". (So, `.allow_element()` plus some kind of URI filter)

Hi I know this issue is closed, but in 2023 do we have a way to allow iframe with specific src address, such as youtube ?

**Comment by gengjun** [comment]
> 3. Allow fine customization so users can easily ask for things like "Defaults, but also allow `script` tags pointing at GitHub Gist and `iframe` tags pointing at Youtube". (So, `.allow_element()` plus some kind of URI filter)

in 2023, is it possible to whitelist iframe, but only allow src from youtube ? The closest thing i found is using add_tag_attribute_values, but this is for exact match of src address, you can not say all address from youtube.
