### ISSUE TITLE
Panics with UrlRelative::RewriteWithBase 

### ISSUE THREAD

**Issue by jolhoeft** [notriddle/ammonia#68]
If the base url given to RewriteWithBase does not parse according to the Url crate, Ammonia::clean_dom will panic. This is a runtime error that can be hard to track down. A couple suggestions:

 * Have RewriteWithBase take a Url instead of an str. The caller can then handle parse errors by whatever policy they have in place for their application.

 * Have the clean function return a Result with an enum of errors. This may be more generally useful, but a more complex interface.

I notice a number of other places in the code where a panic (usually via expect) is possible. I'd rather not have this, because it make catching these errors difficult. Panic kills the current thread, while I would like to log the error and serve up an error page.

**Comment by notriddle** [comment]
Mostly, the crate is designed with the assumption that if it's possible for your app to set up a bad configuration, your app should just check it itself. Since most of Ammonia's configuration ends up hard-coded in the app anyway, the error conditions won't be found outside of development.

The rest of them are based on DOM invariants like "`self.parent.children` contains `self`," so they really are impossible to hit unless something is wrong with Ammonia or HTML5ever.

Though, thinking about it, neither of these are typically the case for relative URLs. Those get constructed partially out of user input in many common cases. Since the `url` crate is past 1.0, we should be able to make it a part of the public API surface. Does anybody have objections to making `url` a part of the public interface? If not, I'll make that switch and publish 1.0-rc2.
