### ISSUE TITLE
wondering why inline `width` and `height` property aren't filtered

### ISSUE THREAD

**Issue by StyMaar** [notriddle/ammonia#86]
It looks like ammonia filters the inline `style` property from html tags, but not the `width` and `height` properties (on an `<img>` tag). 

Is it on purpose ? What's the rational about it ?

Example : 

```html
<img height="3000px" src="http://example.org/image.png" />
```

**Comment by lnicola** [comment]
Allowing arbitrary CSS is more dangerous than allowing custom `width` and `height` elements, since you can use it to inject content into the page, like in https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.234_-_CSS_Escape_And_Strictly_Validate_Before_Inserting_Untrusted_Data_into_HTML_Style_Property_Values.

Setting image dimensions is safe compared to that, but you can disallow that, too, using https://docs.rs/ammonia/1.0.0/ammonia/struct.Builder.html#method.rm_tag_attributes.

**Comment by StyMaar** [comment]
Thanks for your answer. 
Actually I realize that allowing custom `width` and `height` is no more dangerous than allowing images in the first place and I understand why one would like images to be allowed by default.

**Comment by lnicola** [comment]
Exactly, that was the other argument I wanted to make.
